package Tawsif.HumanResourcesManagerControllers;

import Tawsif.Models.HRReport;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;

import java.io.IOException;
import java.time.LocalDate;

public class HumanResourcesReports_Controller {

    @FXML
    private Label userLabel;

    @FXML
    private ComboBox<String> reportTypeComboBox;

    @FXML
    private DatePicker reportDatePicker;

    @FXML
    private TextField generatedByField;

    @FXML
    private TableView<HRReport> reportTableView;

    @FXML
    private TableColumn<HRReport, String> reportIdColumn;

    @FXML
    private TableColumn<HRReport, String> reportTypeColumn;

    @FXML
    private TableColumn<HRReport, LocalDate> reportDateColumn;

    @FXML
    private TableColumn<HRReport, String> generatedByColumn;

    @FXML
    private Label totalReportsLabel;

    @FXML
    private Label statusLabel;

    private final ObservableList<HRReport> reportList =
            FXCollections.observableArrayList();

    @FXML
    public void initialize() {

        reportTypeComboBox.getItems().addAll(
                "Attendance Report",
                "Payroll Report",
                "Leave Report",
                "Employee Directory",
                "Employee Separation"
        );

        reportIdColumn.setCellValueFactory(new PropertyValueFactory<>("reportId"));
        reportTypeColumn.setCellValueFactory(new PropertyValueFactory<>("reportType"));
        reportDateColumn.setCellValueFactory(new PropertyValueFactory<>("reportDate"));
        generatedByColumn.setCellValueFactory(new PropertyValueFactory<>("generatedBy"));

        reportTableView.setItems(reportList);

        totalReportsLabel.setText("0");
        userLabel.setText("HR Manager");
        statusLabel.setText("Ready");
    }

    @FXML
    public void handleGenerateReport(ActionEvent event) {

        if (reportTypeComboBox.getValue() == null
                || reportDatePicker.getValue() == null
                || generatedByField.getText().isEmpty()) {

            statusLabel.setText("Please complete all fields.");
            return;
        }

        String reportId = "REP" + (reportList.size() + 1);

        HRReport report = new HRReport(
                reportId,
                reportTypeComboBox.getValue(),
                reportDatePicker.getValue(),
                generatedByField.getText()
        );

        reportList.add(report);

        totalReportsLabel.setText(String.valueOf(reportList.size()));

        statusLabel.setText("Report Generated Successfully.");
    }

    @FXML
    public void handleSearch(ActionEvent event) {

        String generatedBy = generatedByField.getText().trim();

        if (generatedBy.isEmpty()) {
            statusLabel.setText("Enter Generated By.");
            return;
        }

        for (HRReport report : reportList) {

            if (report.getGeneratedBy().equalsIgnoreCase(generatedBy)) {

                reportTypeComboBox.setValue(report.getReportType());
                reportDatePicker.setValue(report.getReportDate());

                reportTableView.getSelectionModel().select(report);

                statusLabel.setText("Report Found.");
                return;
            }
        }

        statusLabel.setText("Report Not Found.");
    }

    @FXML
    public void handleRefresh(ActionEvent event) {

        reportTableView.refresh();

        totalReportsLabel.setText(String.valueOf(reportList.size()));

        statusLabel.setText("Table Refreshed.");
    }

    @FXML
    public void handleClear(ActionEvent event) {

        reportTypeComboBox.getSelectionModel().clearSelection();
        reportDatePicker.setValue(null);
        generatedByField.clear();

        reportTableView.getSelectionModel().clearSelection();

        statusLabel.setText("Fields Cleared.");
    }

    @FXML
    public void handleBack(ActionEvent event) {

        try {

            FXMLLoader loader = new FXMLLoader(
                    getClass().getResource(
                            "/com/example/group66_ms3version1_carmanufacturingcompanytoyota_2521797_2521122_2520946_2521060/Tawsif/HumanResourcesManager/HumanResourcesManagerDashboardView.fxml"
                    )
            );

            Scene scene = new Scene(loader.load());

            Stage stage = (Stage) statusLabel.getScene().getWindow();

            stage.setScene(scene);
            stage.setTitle("Human Resources Dashboard");
            stage.show();

        } catch (IOException e) {

            statusLabel.setText("Unable to open Dashboard.");
            e.printStackTrace();
        }
    }
}